version: '3'

services:
  nginx-nexusproxy:
    hostname: nginx-proxy  
    container_name: nginx-proxy
    image: nginx-nexus-proxy
    ports:
      - '443:443'
      - '5001:5001'  
      - '5002:5002'  
    links:
      - nexus-repo
    command: [ nginx, '-g', 'daemon off;' ]

  nexus-repo:
    hostname: nexus-repo      
    container_name: nexus-repo
    image: sonatype/nexus3
    ports:
       - '8081:8081'
       - '8085:8085'
       - '8086:8086'  
       - '8087:8087'  
    volumes:
      - 'nexus3-data:/nexus-data'

volumes:
  nexus3-data:
