version: '3'

services:
  nginx-nexusproxy:
    hostname: nginx  
    container_name: nginx    
    image: nginx-nexusproxy
    ports:
      - '443:443'
      - '5085:5085'  
      - '5086:5086'  
        # - '5000:5000'
        # - '5001:5001'
        # - '5002:5002'
        # - '5003:5003'
        # - '5004:5004'
        # - '5005:5005'
    links:
      - nexus-repo
    command: [ nginx, '-g', 'daemon off;' ]

  nexus-repo:
    hostname: nexus-repo      
    container_name: nexus-repo
    image: sonatype/nexus3
    ports:
       - '8081:8081'
       - '8085:8085'
       - '8086:8086'  
    volumes:
      - 'nexus3-data:/nexus-data'

volumes:
  nexus3-data:
